server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://数据库:3306/r_mall?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: HikariCP

  redis:
    host: redis ip
    port: 6379
    password: redis 密码
    database: 0
    timeout: 5000
    jedis:
      pool:
        max-idle: 6
        max-active: 32
        max-wait: 10000
        min-idle: 500
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  data:
    mongodb:
      uri: mongodb://mongodb 地址
      password: mongodb 密码
      database: 库名
      username: mongodb 用户名

dubbo:
    application:
      name: member-provider
    registry:
      address:  nacos 地址
      port: 8848
    protocol:
      name: dubbo
      port: 20881
      serialization: kryo
mybatis:
  mapper-locations: classpath:mapper/*.xml


logging:
  config: classpath:logging.xml